import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/03b90cca97.js"
          crossorigin="anonymous"
          async
        ></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
